name: Contenttrain
favicon: null
layout_spectrum: 0.73889
typography_spectrum: 0.75479
title: The contentroom of Cypres
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#999999'
    - '#333335'
    - '#ff1e00'
    - '#fe7967'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
